controllers_manager:
  ros_parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
 ros_parameters:
  left_wheel_names: ["front_left_wheel","rear_left_wheel"]
  left_wheel_names: ["front_right_wheel","rear_right_wheel"]
  
  wheels_per_side: 1

  wheel_separation:
  wheel_radius: 0.127

  odom_frame_id: "odom"
  base_frame_id: "base_link"

  enable_odom_tf: true
  publish_rate: 50.0

  linear.x.max_velocity: 1.0
  linear.x.min_velocity: -1.0
  angular.z.max_velocity: 1.0
  angular.z.min_velocity: -1.0
